<?php

namespace blogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
    public function buscaComentarios($id){

        return $this->getEntityManager()
            ->createQuery("
                    SELECT c.id, c.contenido, c.usuarioId, c.mensajeId, m.id, u.id, u.nombreUsuario
                    FROM blogBundle:Comentario c, blogBundle:Mensaje m, blogBundle:Usuario u
                    WHERE c.mensajeId = '$id' and m.id = c.mensajeId and c.usuarioId = u.id
                    ORDER by c.id DESC 
                ")
            ->getResult();
    }
}
