blog_homepage:
    path:     /
    defaults: { _controller: blogBundle:Default:index }

blog_entrada:
    path:     /entrada/{id}
    defaults: { _controller: blogBundle:Default:entrada }
    
blog_login:
    path:     /login
    defaults: { _controller: blogBundle:Login:index }
    
blog_logout:
    path:     /logout
    defaults: { _controller: blogBundle:Login:logout }